apiVersion: batch/v1
kind: CronJob
metadata:
  name: brew-buddy-scraper-cron
spec:
  schedule: "0 */6 * * *" # At minute 0, every 6 hours
  concurrencyPolicy: Forbid  # Don't run two scrapes at once
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            seccompProfile:
              type: "RuntimeDefault"
          containers:
          - name: scraper
            image: local-registry.io/brew-buddy:latest
            command: ["/app/brew-buddy"]
            args: ["scrape"]
            env:
            - name: DB_PATH
              value: /data/coffee.db
            - name: CONFIG_PATH
              value: /app/config.yaml
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: brew-buddy-secret
                  key: GEMINI_API_KEY
            volumeMounts:
            - name: data-storage
              mountPath: /data
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
          volumes:
          - name: data-storage
            persistentVolumeClaim:
              claimName: brew-buddy-data-pvc
          - name: config-volume
            configMap:
              name: brew-buddy-config
